config/routes.rb
Rails.application.routes.draw do

devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

scope module: :public do
  root to: 'homes#top'
  get 'about' => 'homes#about'
  resources :primes, only:[:new, :create]
  get 'primes/:id/answers' => 'primes#answers', as: :answer
end

namespace :admin do
  resources :blogs, only:[:index, :show, :create, :new]
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/prime.rb
class Prime < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/blogs_controller.rb
class Admin::BlogsController < ApplicationController
  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.save
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def index
    @blogs = Blog.all
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :body)
  end

end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Admin::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/registrations_controller.rb
# frozen_string_literal: true

class Admin::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_out_path_for(resource)
    root_path
  end
end

app/helpers/admin/blogs_helper.rb
module Admin::BlogsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/blogs/index.html.erb
<div class="container">
  <div class="row">
    <div class="col mx-auto">
      <h3 class="m-3 text-center">
        <i class="fas fa-smile"></i> 投稿一覧 <i class="fas fa-smile"></i>
      </h3>
    </div>
  </div>
  <div class="row">
    <div class="mx-auto col-12 col-md-10 col-lg-10">
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th>Title</th>
            <th>Body</th>
          </tr>
        </thead>
        <tbody>
          <% @blogs.each do |blog| %>
            <tr>
              <td><%= link_to blog.title,admin_blog_path(blog.id) %></td>
              <td><%= blog.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/blogs/new.html.erb
<div class="container">
  <div class="row">
    <div class="col mx-auto">
      <h3 class="m-3 text-center">新規投稿</h3>
    </div>
  </div>
  <%= form_with model: @blog, url: admin_blogs_path,method: :post,local:true do |f| %>
    <div class="row">
      <div class="mx-auto col-10 col-md-6 col-lg-5 pt-lg-5 pt-md-5">
        <div class="form-group">
          <%= f.label :タイトル %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :本文 %>
          <%= f.text_area :body, class: "form-control" %>
        </div>
        <div class="form-group my-5 pt-lg-3 text-center">
          <%= f.submit"投稿",class: "btn btn-success" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/blogs/show.html.erb
<div class="container">
  <div class="row">
    <div class="col mx-auto">
      <h3 class="m-3 text-center">投稿</h3>
    </div>
  </div>
  <div class="row">
    <div class="mx-auto col-10 col-md-6 col-lg-5 pt-lg-5 pt-md-5">
      <h4>
        <%= @blog.title %>
      </h4>
      <h6>
        <%= @blog.body %>
      </h6>
    </div>
  </div>
</div>

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col py-4">
        <div class="text-center py-2">
          © 2022 prime.Inc
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg">
    <div class="container">
      <a class="navbar-brand" href="/"><%= image_tag"prime.png",size: "250x75" %></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to(new_prime_path, class: "nav-link btn btn-light mx-3") do %><i class="fas fa-star"></i> 検索<% end %>
              </li>
            <% elsif admin_signed_in? %>
              <li class="nav-item">
                <%= link_to(admin_blogs_path, class: "nav-link btn btn-light mx-3") do %><i class="fas fa-star"></i> ブログ一覧<% end %>
              </li>
              <li class="nav-item">
                <%= link_to(new_admin_blog_path, class: "nav-link btn btn-light mx-3") do %><i class="fas fa-star"></i> ブログ投稿<% end %>
              </li>
              <li class="nav-item">
                <%= link_to(destroy_admin_session_path, method: :delete, class: "nav-link btn btn-light mx-3") do %><i class="fas fa-star"></i> ログアウト<% end %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to(about_path, class: "nav-link btn btn-light mx-2") do %><i class="fas fa-star"></i> 使い方<% end %>
              </li>
            <% end %>
          </ul>
        </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
      <main>
        <%= yield %>
      </main>
    <%= render "layouts/footer" %>
  </body>
</html>